[package]
name = "wireguard-nt"
version = "1.0.0"
edition = "2018"
authors = ["null.black Inc. <opensource@null.black>", "Troy Neubauer <troy@null.black>"]
repository = "https://github.com/nulldotblack/wireguard-nt"
readme = "README.md"
documentation = "https://docs.rs/wireguard-nt/"
description = "Safe idiomatic bindings to the Wireguard NT C library"
license = "MIT"
keywords = ["wireguard", "vpn", "windows"]
categories = ["api-bindings"]

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = ["aarch64-pc-windows-msvc", "i686-pc-windows-msvc", "x86_64-pc-windows-msvc"]

[features]
ciphers_extension = ["wireguard-uapi/ciphers_extension"]

[dependencies]
tracing = "0.1.44"
winapi = { version = "0.3", features = ["ws2def", "netioapi", "nldef"] }
wireguard-uapi = { git = "https://github.com/tomasz-kumor/wireguard-uapi-rs.git", branch = "LLT-7574-wiregard-uapi", features = ["xplatform", "zeroize"] }
bitflags = "2"
getrandom = "0.4"
ipnet = "2.12"
libloading = "0.9"
log = "0.4"
thiserror = "2.0"
widestring = "1.2"
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Networking",
    "Win32_Networking_WinSock",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis"
]}

[dev-dependencies]
base64 = "0.22"
neptun = { git = "https://github.com/tomasz-kumor/NepTUN", branch="LLT-7574-aead-cipher-suites-support" }
env_logger = "0.11"
x25519-dalek = { version = "2", default-features = false, features = ["static_secrets", "getrandom"] }
